# Site settings
title: Waris Ali
description: >-
  He's writing in Pakistan about web technology and experience as a journal for documenting things that he learned, meet him <a href="https://github.com/warisali2" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Asia/Karachi
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/warisali2/warisali.github.io
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Waris Ali
  bio: >-
    Hi, I am a Backend Web Developer @ <a href="https://pakwheels.com" target="_blank" rel="noopener">PakWheels</a>.<br/> I write about what I know and break down complex concepts in accessable and intuitive way.
  username: warisali2
  email: contact@warisali.tech
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://warisali.tech"
baseurl:
permalink: /:title/
google_analytics: UA-166763516-1
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - notes.md
  - .idea

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
